/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Granular */

#ifndef _Included_Granular
#define _Included_Granular
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: procColor */
#undef Granular_serialVersionUID
#define Granular_serialVersionUID 213i64
#undef Granular_serialVersionUID
#define Granular_serialVersionUID 213i64
/* Inaccessible static: threadId */
#undef Granular_serialVersionUID
#define Granular_serialVersionUID 213i64
/*
 * Class:     Granular
 * Method:    setMaxGrains
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Granular_setMaxGrains
  (JNIEnv *, jobject, jint);

/*
 * Class:     Granular
 * Method:    setNormalized
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Granular_setNormalized
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Granular
 * Method:    setAmplitudeModulation
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Granular_setAmplitudeModulation
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Granular
 * Method:    addGrainSource
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Granular_addGrainSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Granular
 * Method:    setSourceProbability
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Granular_setSourceProbability
  (JNIEnv *, jobject, jint);

/*
 * Class:     Granular
 * Method:    initSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Granular_initSound
  (JNIEnv *, jobject);

/*
 * Class:     Granular
 * Method:    stopSound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Granular_stopSound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
